language: go
sudo: false
go:
  - 1.9.x

git:
  depth: 3

install:
  - make install

go_import_path: github.com/weiwei99/ats

script:
  - make vet
  - make fmt-check
  - make embedmd
  - make misspell-check
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7f95bf605c4d356372f4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
